service: http-lambda-dynamodb
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "*"

functions:
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /todos
          method: get
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /todos
          method: post
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: put
  

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH